创建 zh-CN 目录用于存放中文翻译版本，并将之前 GCTT 翻译好的文章加进来
studygolang/learn-go-with-tests pull request #1
Opened 2018-06-04 07:34 UTC by polaris1119

2018-06-04 08:53 UTC, pityonline commented on zh-CN/README.md
> +
空行使用一行即可。

2018-06-04 12:17 UTC, pityonline commented on zh-CN/README.md
> +# 目录
同一个 Markdown 文件中不应出现两个一级标题。这一行可以省略。

2018-06-04 13:12 UTC, Donng commented on zh-CN/dependency-injection.md
> +**[您可以在这里找到本章的所有代码](https://github.com/quii/learn-go-with-tests/tree/master/di)**
使用 "您" 或者是  "你"，应该做到全文统一。

2018-06-04 13:15 UTC, Donng commented on zh-CN/dependency-injection.md
> +本例深深受到 [The Go Programming language](https://www.amazon.co.uk/Programming-Language-Addison-Wesley-Professional-Computing/dp/0134190440) 中一个章节的启发，如果你喜欢的话，去它买吧！
去买它吧 ？

2018-06-04 13:15 UTC, Donng commented on zh-CN/dependency-injection.md
> +
原文链接没有提供

2018-06-04 13:19 UTC, pityonline requested changes
@polaris1119 本次 review 我针对一些易于修订的格式问题提了一些小建议，请参考。

主要 review 工具和方法：

* [markdownlint](https://github.com/markdownlint/markdownlint)
* vim
* `git log -p`
* `git apply pr-1.patch`

因译文已在 studygolang/GCTT 评审校对过，所以本次默认为无问题，后续如发现问题可提 PR 修订。

2018-06-04 13:19 UTC, pityonline commented on zh-CN/README.md
> +* [Chapter Template](template.md) 未翻译
这个 README 如果作为翻译进度展示，可使用 ToDo list 格式。

## chapter

* [ ] [section 1](target1)
* [ ] [section 2](target2)

2018-06-04 13:19 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +`go test -cover`
这里有一个行尾空白。

2018-06-04 13:19 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +
这里有三个行尾空白。

2018-06-04 13:19 UTC, pityonline commented on zh-CN/dependency-injection.md
> +就像我们在 hello-world 篇做的那样，我们想要编写一个欢迎某人的函数，只不过这次我们希望测试实际的打印（actual printing）。
14 和 12 行有多余行尾空白，请移除，其它文件下同。

2018-06-04 13:19 UTC, pityonline commented on zh-CN/dependency-injection.md
> +- **使得代码可以在不同环境下重用**。我们的代码所处的第一个“新”环境就是在运行的测试。但是随后，如果其他人想要用你的代码尝试点新东西，他们只要注入他们自己的依赖就可以了。
9-12 行使用 `*` 作为无序列表标记，这里使用了 `-` 作为无序列表标记，同一文档内请使用相同的标记。参考 markdownlint Rules [MD004 - Unordered list style](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md004---unordered-list-style)

2018-06-04 13:19 UTC, pityonline commented on zh-CN/mocking.md
> +- 你正在进行的测试需要做太多的事情
不同元素（正文文本和无序列表）之间应尽量用一个空行隔开，避免有时候出现渲染问题导致格式错乱（有时候会被连成一行）。

2018-06-04 13:19 UTC, pityonline commented on zh-CN/mocking.md
> +	- 最好测试预期的行为，而不是功能的实现
使用多层列表时，缩进应该使用空格，[markdownlint 默认使用 2 个空格](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md007---unordered-list-indentation)，我认为 2 个或 4 个都可以，可以参考原文写法。

2018-06-04 13:19 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
这里有个 `\ No newline at end of file` 的问题，文件尾应该有一个换行，但不要有多余换行，请参考 [What's the point in adding a new line to the end of a file?](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)

2018-06-04 13:19 UTC, pityonline commented on zh-CN/README.md
> +# 目录
同一个 Markdown 文件中不应出现两个一级标题。这一行可以省略。

2018-06-05 01:42 UTC, pityonline approved these changes

2018-06-05 02:16 UTC, merged