gb-readme.md
studygolang/learn-go-with-tests pull request #14
Opened 2018-06-21 08:30 UTC by Donng

有几个不太确定的地方：
- grounding
- kata
- ad hoc

2018-06-21 11:44 UTC, flw-cn commented on zh-CN/gb-readme.md
> +这最终会使学习变得非常 _凌乱无序_。
ad hoc 确实不太好译，但我看了一下原文，它在这里不起到主要的表意作用。所以赞同移译的做法。

倒是 kata 如果不译好的话这一节有一大半的意思就全都遗失了。
查了一下，似乎 kata 是日语？这个估计得请教一下 quii 了。

2018-06-22 14:30 UTC, pityonline commented on zh-CN/gb-readme.md
> +* **上手测试驱动开发。** Go 是学习测试驱动开发的好语言，因为它简单易学而且内置测试功能
原文是

```
**Get a grounding with TDD**.
```

句号放在粗体标签外面也没关系，只是发现了顺便提一下。

2018-06-22 14:51 UTC, pityonline requested changes
@Donng 提了几点小建议，另外请把 Commit Message 标题和 PR 标题修改一下吧，参照之前提交的格式

* 【翻译完成】xxx.md
* 更新翻译进度，完成 iteration 翻译

2018-06-22 14:51 UTC, pityonline commented on zh-CN/gb-readme.md
> +我喜欢这本书，但它需要高度的投入。这本书非常详细地解释了每个概念，这显然是极好的，但也意味着进步是缓慢而稳定的 -- 这不适用于每个人。
这里出现两个半角的 `-` 不太协调，建议使用中文全角的 ` —— `。

2018-06-22 14:51 UTC, pityonline commented on zh-CN/gb-readme.md
> +[Kata](https://en.wikipedia.org/wiki/Kata_(programming))[^注1] 很有趣，但是他们学习语言的范围通常是有限的；你不太可能用 go 例程来解决 kata 问题。
建议把 *go 例程* 中的 `g` 大写。

2018-06-22 14:51 UTC, pityonline commented on zh-CN/gb-readme.md
> +这最终会使学习变得非常 _凌乱无序_。
维基百科有几种 [ad hoc](https://zh.wikipedia.org/wiki/Ad_hoc) 的解释：

> Ad hoc 是拉丁文常用短语中的一个短语。这个短语的意思是“特设的、特定目的的（地）、即席的、临时的、将就的、专案的”。这个短语通常用来形容一些特殊的、不能用于其它方面的，为一个特定的问题、任务而专门设定的解决方案。这个词汇须与 a priori 区分。

根据上下文来看，感觉是`无系统地学习，每次都要现学、现查`的意思。不翻译出来也挺好，比较通顺。

2018-06-22 14:51 UTC, pityonline commented on zh-CN/gb-readme.md
> +[MIT license](https://github.com/quii/learn-go-with-tests/blob/842f4f24d1f1c20ba3bb23cbc376c7ca6f7ca79a/LICENSE.md)
这里的 commit ID 改成 master 吧，上游 [README.md](https://github.com/quii/learn-go-with-tests/blob/master/README.md) 里也是用的 master，稍后我会提个 PR 给上游把这里改掉。

2018-06-22 14:57 UTC, Donng commented on zh-CN/gb-readme.md
> +[MIT license](https://github.com/quii/learn-go-with-tests/blob/842f4f24d1f1c20ba3bb23cbc376c7ca6f7ca79a/LICENSE.md)
@pityonline 上游 `pr` 通过麻烦说一下

2018-06-22 15:39 UTC, pityonline commented on zh-CN/gb-readme.md
> +[MIT license](https://github.com/quii/learn-go-with-tests/blob/842f4f24d1f1c20ba3bb23cbc376c7ca6f7ca79a/LICENSE.md)
@Donng quii/learn-go-with-tests#86

2018-06-22 16:57 UTC, pityonline approved these changes
LGTM!

2018-06-22 16:58 UTC, merged