【翻译完成】README.md
studygolang/learn-go-with-tests pull request #18
Opened 2018-06-26 10:48 UTC by Donng

2018-06-26 16:27 UTC, pityonline requested changes
@Donng 有几个小建议，未发现其它问题，请看一下。

2018-06-26 16:27 UTC, pityonline commented on zh-CN/README.md
> +如果目录中的标题没有链接，说明它还没有完成！
why not contribute? 应该翻译出来。

2018-06-26 16:27 UTC, pityonline commented on zh-CN/README.md
> +* [JSON, routing and embedding](json.md) - 我们将生成终结点（endpoint）返回 JSON 并探索如何分发路由。
`endpoint` 感觉翻译成`端点`好一些，web 服务用语里这个词挺常见，我看有翻译成端点的。看看 @polaris1119 和 @flw-cn 有什么好的建议？

2018-06-26 16:27 UTC, pityonline commented on zh-CN/README.md
> +* [IO 和排序](io.md) -我们将从磁盘持久化和读取数据，并介绍数据排序。
`-` 符号后面应该有一个空格。

2018-06-26 16:28 UTC, pityonline commented on zh-CN/README.md
> +* _这个项目正在进展中_，如果你想参与贡献，请务必联系。
`请务必联系。`翻译成`请务必联系我。`比较通顺。

2018-06-27 02:02 UTC, Donng commented on zh-CN/README.md
> +如果目录中的标题没有链接，说明它还没有完成！
直译挺尬的，我翻译成： 为什么不一起参与呢？

2018-06-27 04:32 UTC, pityonline approved these changes

2018-06-27 04:33 UTC, merged