【翻译完成】json.md
studygolang/learn-go-with-tests pull request #19
Opened 2018-07-02 04:40 UTC by pityonline

2018-07-02 08:12 UTC, polaris1119 requested changes
初步发现的一些问题

2018-07-02 08:12 UTC, polaris1119 commented on zh-CN/json.md
> +在上一章中，我们创建了一个 web 服务器用来储存多少玩家赢了（游戏）。
上一章是不是跟原文一样，保留链接？

2018-07-02 08:12 UTC, polaris1119 commented on zh-CN/json.md
> +我们的项目负责人有个新的需求，要求有一个叫 `/league`（联盟）的新的端点，它可以返回一个玩家清单。她想让它返回一个 JSON 格式的数据。
端点，是否需要保留 endpoint 这个原文？

2018-07-02 08:12 UTC, polaris1119 commented on zh-CN/json.md
> +- 最终，我们通过调用新路由的 `ServeHTTP` 方法处理了的请求（注意到 `ServeMux` 也是一个 `http.Handler` 了吗？）
> 最终，我们通过调用新路由的 `ServeHTTP` 方法处理了的请求

此句有些不太通顺，建议：

我们通过调用新路由的 `ServeHTTP` 方法处理到来的请求

2018-07-02 08:12 UTC, polaris1119 commented on zh-CN/json.md
> +我们更改了 `PlayerServer` 的第二个属性，删除了命名属性`router http.ServeMux`，并用 `http.Handler` 替换了它；这被称为 _嵌入_。
名属性`router http.ServeMux` 少个空格

2018-07-02 08:12 UTC, polaris1119 commented on zh-CN/json.md
> +> Go 没有提供典型的，类型驱动的子类化概念，但它具有通过在结构或接口中嵌入类型来“借用”实现的能力。
应该是：“借用”实现部分？

2018-07-02 08:12 UTC, polaris1119 commented on zh-CN/json.md
> +如果我们懒一点，嵌入了 `http.ServeMux`（混合类型），它仍然可以工作 _但_ `PlayerServer` 的用户就可以给我们的服务器添加新路由了，因为 `Handle)path, handler)` 会公开。
`Handle(path, handler)` 括号错了

2018-07-02 15:26 UTC, pityonline commented on zh-CN/json.md
> +在上一章中，我们创建了一个 web 服务器用来储存多少玩家赢了（游戏）。
需要，这里是我遗漏了，已修正。谢谢指出。

2018-07-02 15:28 UTC, pityonline commented on zh-CN/json.md
> +我们的项目负责人有个新的需求，要求有一个叫 `/league`（联盟）的新的端点，它可以返回一个玩家清单。她想让它返回一个 JSON 格式的数据。
README.md 翻译中保留过，如果这个词在某章中首次出现，保留原文是比较好的。后续我们可以加一个词汇表。

2018-07-02 15:31 UTC, pityonline commented on zh-CN/json.md
> +- 最终，我们通过调用新路由的 `ServeHTTP` 方法处理了的请求（注意到 `ServeMux` 也是一个 `http.Handler` 了吗？）
谢谢指出，已修正。

2018-07-02 15:31 UTC, pityonline commented on zh-CN/json.md
> +我们更改了 `PlayerServer` 的第二个属性，删除了命名属性`router http.ServeMux`，并用 `http.Handler` 替换了它；这被称为 _嵌入_。
好眼力！已修正。

2018-07-02 15:36 UTC, pityonline commented on zh-CN/json.md
> +> Go 没有提供典型的，类型驱动的子类化概念，但它具有通过在结构或接口中嵌入类型来“借用”实现的能力。
> Go does not provide the typical, type-driven notion of subclassing, but it does have the ability to “borrow” pieces of an implementation by embedding types within a struct or interface.

to "borrow" pieces of an implementation 是借用一部分实现？或者借用实现的一部分？改成`但它具有通过在结构或接口中嵌入类型来“借用”一部分实现的能力。`怎么样？

2018-07-03 00:43 UTC, pityonline commented
@polaris1119 已根据校对意见进行修订，请检查。

2018-07-03 13:11 UTC, flw-cn commented on zh-CN/json.md
> +我们的项目负责人有个新的需求，要求有一个叫 `/league`（联盟）的新的端点，它可以返回一个玩家清单。她想让它返回一个 JSON 格式的数据。
endpoint 确实不太好翻译。端点这个说法之前也很少见到。这里实际上面临一个问题就是我们到底要翻译到什么程度。

2018-07-04 01:22 UTC, polaris1119 approved these changes

2018-07-04 01:46 UTC, merged