【翻译完成】io.md
studygolang/learn-go-with-tests pull request #21
Opened 2018-07-05 06:22 UTC by Donng

2018-07-07 05:31 UTC, pityonline requested changes
@Donng 有一些小的修改意见，请查阅。

结合上下文，这几章都是在以一个游戏为例展开叙述，所有译为`球员`的地方都应译为`玩家`，建议 `score` 都译为`得分`。这里我没有一一指出，可以批量替换后再检查变更。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +服务器重启后软件会丢失所有分数，产品负责人对此感到不安。这是因为我们存储的实现是在内存里。对于我们没有解释 `/league` 的访问地址应该按赢球数排序返回球员，她也很不满意。
> should return the players ordered by number of wins!

这里是`应该按赢的次数排序返回玩家列表`，和球员应该没有关系。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +如果我们回到 `FileSystemStore.go`。我们在构造函数中有 `league， _:= NewLeague(f.database)`。
`league， _:= NewLeague(f.database)` 代码引用应该使用半角的 `,` 逗号。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +在我们的实现和 `server_test.go` 的测试助手 `getLeagueFromResponse` 中调用这个函数
建议 `helper` 都译为`辅助函数`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +我们可以遍历 `league` 寻找球员并返回他们的分数
结合上下文，这几章都是在以一个游戏为例展开叙述，所有译为`球员`的地方都应译为`玩家`，建议 `score` 都译为`得分`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +在 `TestRecordingWinsAndRetrievingThem` 中，替换之前的存储。
> In `TestRecordingWinsAndRetrievingThem` replace the old store.

建议将 `store` 译为`记录`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +- 第 3 个参数表示设置文件的权限，在我们的示例中，所有用户都可以读写文件。[（详情请参阅 superuser.com）](https://superuser.com/questions/295591/what-is-the-meaning-of-chmod-666)
句尾应加一个 `。` 号。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +重启运行程序，现在将持久化数据到文件中。
原文中有个 `hooray!`，一般是`万岁！`的意思，结合上下文，建议译出为`太棒了！`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +最后，我们可以通过从 `RecordWin` 中删除 `Seek` 调用来获得我们想要的惊人回报。是的，这感觉并不多，但至少这意味着如果我们做任何其他类型的写入操作，我们可以依赖 `write` 来表达我们对它的需求。此外，它现在将允许我们分别测试可能存在问题的代码并修复它。
> 但至少这意味着如果我们做任何其他类型的写入操作

`其他`建议替换为`其它`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +让我们编写一个测试，我们想用比原始内容更小的东西来更新文件的整个内容。在 `tape_test.go`:
> 在 `tape_test.go`:

建议改成这样，更通顺一些，并使用中文冒号。

```
在 `tape_test.go` 中：
```

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +但这有什么好处呢？请记住，我们并不是在故意嘲笑，**文件系统**存储采取除 `*os.File` 之外的任何类型都是不现实的。所以我们不需要接口给我们的多态性。
> 请记住，我们并不是在故意嘲笑

`mocking` 在这里应译为`模拟`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +在开始排序之前，我们应该确保对当前代码感到满意，并删除可能存在的任何技术债务。尽可能快地使用软件（脱离红色状态）是一个重要的原则，但这并不意味着我们应该忽略错误案例！
`error cases` 建议译为`出错的场景`，会更通顺一些。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +请记住，提供有用的错误信息非常重要(就像你写的测试一样)。人们在网上开玩笑说大多数 Go 代码都是
`()` 应改为`（）`，中文语境应使用中文标点符号。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +我们的产品所有者想让 `/league` 返回按分数排序的球员。
`product owner` 建议译为`产品负责人`。

2018-07-07 05:31 UTC, pityonline commented on zh-CN/io.md
> +- 使用文件存储。
> Working with files.

建议译为`处理文件读写`。

2018-07-07 06:30 UTC, Donng commented on zh-CN/io.md
> +重启运行程序，现在将持久化数据到文件中。
其实这个一开始我是拒绝的，强行加上去感觉好违和。

2018-07-07 06:30 UTC, Donng commented on zh-CN/io.md
> +重启运行程序，现在将持久化数据到文件中。
@pityonline 其实这个一开始我是拒绝的，强行加上去感觉好违和。

2018-07-07 10:11 UTC, pityonline requested changes
@Donng 还有几个小问题，请查阅。

`helper` 建议统一翻译成`辅助函数`，避免有的地方叫法不一，就像我们约定分割线使用最少量的 `---` 一样，可以全文搜索并替换一下。

2018-07-07 10:11 UTC, pityonline commented on zh-CN/io.md
> +}
这行下面应该有一个空行。

2018-07-07 10:11 UTC, pityonline commented on zh-CN/io.md
> +让我们创建一个助手函数，它将创建包含一些数据的临时文件
助手函数 => 辅助函数。

2018-07-07 10:11 UTC, pityonline commented on zh-CN/io.md
> +你会注意到，我们不仅返回 `ReadWriteSeeker`（文件），而且还返回一个函数。我们需要确保在测试完成后删除该文件。我们不希望将文件的细节泄露到测试中，因为它很容易出错，对读者来说也没什么意思。通过返回 `removeFile` 函数，我们可以处理助手函数中的细节，调用者只需运行 `deferred cleanDatabase()`。
建议`助手函数`统一使用`辅助函数`。

2018-07-07 10:11 UTC, pityonline commented on zh-CN/io.md
> +让我们编写一个测试，我们想用比原始内容更小的东西来更新文件的整个内容。在 `tape_test.go` 中:
中文语境中应使用全角的`：`。

2018-07-07 10:11 UTC, pityonline commented on zh-CN/io.md
> +但这有什么好处呢？请记住，我们并不是在模仿，**文件系统**存储采取除 `*os.File` 之外的任何类型都是不现实的。所以我们不需要接口给我们的多态性。
结合上下文，这里使用`模拟`更恰当一些。

2018-07-07 10:11 UTC, pityonline commented on zh-CN/io.md
> +}
这里多了一个 `}`，已在 quii/learn-go-with-tests#100 中修订，这里也修订一下吧。

2018-07-07 15:46 UTC, Donng commented on zh-CN/io.md
> +但这有什么好处呢？请记住，我们并不是在模仿，**文件系统**存储采取除 `*os.File` 之外的任何类型都是不现实的。所以我们不需要接口给我们的多态性。
**记住，我们并不是在模拟。**  这句话很费解，是模拟什么？

2018-07-07 15:46 UTC, Donng commented on zh-CN/io.md
> +但这有什么好处呢？请记住，我们并不是在模仿，**文件系统**存储采取除 `*os.File` 之外的任何类型都是不现实的。所以我们不需要接口给我们的多态性。
@pityonline 记住，我们并不是在模拟。 这句话很费解，是模拟什么？

2018-07-07 16:00 UTC, pityonline commented on zh-CN/io.md
> +但这有什么好处呢？请记住，我们并不是在模仿，**文件系统**存储采取除 `*os.File` 之外的任何类型都是不现实的。所以我们不需要接口给我们的多态性。
mock 在软件测试中指的是模拟测试，或仿真测试，mocking 那一章讲的就是这个。

模仿的意思更偏向于效仿，学样子，模拟则有以假作真的意思。所以软件测试中用模拟更恰当一些。

2018-07-08 06:23 UTC, pityonline approved these changes

2018-07-08 07:21 UTC, merged