【翻译完成】maps.md
studygolang/learn-go-with-tests pull request #26
Opened 2018-07-24 03:22 UTC by Donng

2018-08-12 13:02 UTC, polaris1119 requested changes

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +Maps 允许你以类似于字典的方式存储值。你可以将`键`视为单词，将`值`视为定义。 难道还有比构建我们自己的字典更好的学习 Maps 的方式吗？
难道还有 前面多了个空格。下面也有类似这样的地方

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +我们实际上得不到任何返回。这很好，因为程序可以继续运行，但还有更好的方法。这个函数可以证明该单词不在字典中。这样，用户不会好奇这个单词不存在还是未定义（这看起来可能对于字典没有用。但是，这可能是其他用例的关键场景）。
这样，用户不会好奇这个单词不存在还是未定义

这里似乎是想说，用户会没法区分单词不存在还是为未定义。

@pityonline @flw-cn 你们觉得呢？

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +为了使测试通过，我们使用了一个 Map 查找的有趣属性。它可以返回两个值。第二个值是一个布尔值，表示是否成功找到 `key`。
有趣属性 改为 有趣特性 是不是更好？

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +Maps 有一个有趣的属性，不使用指针传递你就可以修改它们。这是因为 `map` 是引用类型。这意味着它拥有对底层数据结构的引用，就像指针一样。它底层的数据结构是 `hash table` 或 `hash map`，你可以在[这里](https://en.wikipedia.org/wiki/Hash_table)阅读有关 `hash tables` 的更多信息。
类似的，有趣的属性 建议：有趣的特性

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +除了在更新 `dictionary` 和返回错误时切换之外，这个函数看起来几乎与Add完全相同。
与Add完全相同。 -> 与 Add 完全相同。

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +- 了解更多有关**如何创建常量错误**的内容，编写对错误的封装
此处和原文不一致：

- Learned more about errors
    - How to create errors that are constants
    - Writing error wrappers

2018-08-12 13:02 UTC, polaris1119 commented on zh-CN/maps.md
> +- 了解更多有关**如何创建常量错误**的内容，编写对错误的封装
最后的签名：

```
作者：[Chris James](https://dev.to/quii)
译者：[Donng](https://github.com/Donng)
校对：[polaris1119)[https://github.com/polaris1119)

本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
```

2018-08-13 06:08 UTC, Donng commented on zh-CN/maps.md
> +我们实际上得不到任何返回。这很好，因为程序可以继续运行，但还有更好的方法。这个函数可以证明该单词不在字典中。这样，用户不会好奇这个单词不存在还是未定义（这看起来可能对于字典没有用。但是，这可能是其他用例的关键场景）。
@polaris1119 这句可能意思不太明确，改成  `用户就不用猜测这个单词是不存在还是未定义了`

2018-08-13 06:11 UTC, Donng commented on zh-CN/maps.md
> +- 了解更多有关**如何创建常量错误**的内容，编写对错误的封装
这里应该是原文又修改了。

2018-08-13 15:03 UTC, pityonline requested changes
@Donng 我已校对并发 PR 到 Donng#2 了，请查阅。

2018-08-13 15:03 UTC, pityonline commented on zh-CN/maps.md
> +作者：[Chris James](https://dev.to/quii)
@Donng 这一章的原作者应该是 @hackeryarn。

2018-08-14 10:04 UTC, pityonline approved these changes

2018-08-14 10:36 UTC, merged