【翻译完成】reflection.md
studygolang/learn-go-with-tests pull request #28
Opened 2018-09-07 08:42 UTC by Donng

2018-09-08 15:43 UTC, pityonline requested changes
@Donng WIP: 我先初步看了下格式，有几处小问题，明天我再好好看看。

2018-09-08 15:43 UTC, pityonline commented on zh-CN/reflection.md
> +- 作为函数的使用者，使用 `interface` 将失去对类型安全的检查。如果你想传入 `string` 类型的 `Foo.bar` 但是传入的是 `int` 类型的 `Foo.baz`，编译器将无法通知你这个错误。你也搞不清楚函数允许传递什么类型的参数。知道一个函数接收什么类型，例如 `UserService` ，是非常有用的。
> 例如 `UserService` ，

`，`前不需要再加空格了。

2018-09-08 15:43 UTC, pityonline commented on zh-CN/reflection.md
> +
有序列表，无序列表之前建议不要留空行。

2018-09-08 15:43 UTC, pityonline commented on zh-CN/reflection.md
> +下一个场景是，如果它不是一个 「平的」`struct` 怎么办？换句话说，如果我们有一个包含嵌套字段的 `struct` 会发生什么？
中文全角标点前后不要再加空格了。

2018-09-16 13:19 UTC, pityonline requested changes
@Donng 一些地方需要改一下，比如缺少的几行。其它的和我个人主观喜好相关的留言仅供参考，没必要的话不用修改。辛苦了！

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +### 那么为什么不将所有参数都定义为 `interface` 类型，并得到真正灵活的函数呢？
这句翻译成这样会不会好一点儿？

那么为什么不通过将所有参数都定义为 `interface` 类型来得到真正灵活的函数呢？

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +我们想用一个 `struct` 来调用我们的函数，这个 `struct` 中有一个字符串字段（`x`），然后我们可以监视传入的函数(`fn`)，看看它是否被调用。
(`fn`) 这里应该用全角括号。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +- 我们想存储一个字符串切片（`got`），字符串通过 `walk` 传递到 `fn`。通常在前面的章节中，我们会专门为函数或方法调用指定类型，但在这种情况下，我们可以传递一个匿名函数给 `fn`，它会隐藏 `got`。
> 通常在前面的章节中，我们会...

我觉得用`在前面的章节中，通常我们会...`好一点儿，仅供参考。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +
这里好像少了一行：

> We can call the spy with any string to make this pass.

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +
这里好像少了一段：

## Write the test first

Add the following to the existing test to check the string passed to `fn` is correct

```go
if got[0] != expected {
    t.Errorf("got '%s', want '%s'", got[0], expected)
}
```

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +```
这一段里有一些[零宽空白](https://en.wikipedia.org/wiki/Zero-width_space) `<U+200B>`。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +​
这里也有 `<U+200B>`。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +我们一直在使用匿名结构体语法为我们的测试声明类型，所以我们可以继续这样做
> We have been using the anonymous struct syntax to declare types ad-hocly for our tests so we could continue to do that like so

ad-hoc 应该是临时的意思，所以我认为`一直在`应该是`临时`。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +问题是我们只在类型层次结构的第一级上迭代字段。
这里略有点儿生硬，我觉得可以翻译得更白话一些，如：

这个问题是我们只在类型层次结构的第一级上迭代字段导致的。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +不能对指针 `Value` 使用 `NumField`，我们需要在使用 `Elem()` 之前提取底层值。
这里的 `Value` 感觉有点儿别扭，但没还没弄明白是怎么回事，后面我再看一下。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +如果你抽象地想一下，我们想要在其中任意一个上调用 `walk`
后半句这么翻译是不是好一点儿？

我们想要针对下面的对象调用 `walk`

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +我们目前的代码可以做到这一点，但不能很好地反射。我们只是在一开始检查它是否是切片（通过 `return` 来停止执行剩余的代码），如果不是，我们就假设它是 `struct`。
> 但不能很好地反射

意思是不是说`但反射用得不太好`？

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +看起来好多了！如果是 `struct` 或切片，我们会遍历它的值，并对每个值调用 `walk` 函数。否则如果是 `reflect.String`，我们可以调用 `fn`。
后半句这样翻译会不会更通顺一些？

如果是 `reflect.String`，我们就调用 `fn`。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +不过，对我来说，感觉还可以更好。这里有重复操作遍历字段、值，然后调用 `walk`，但概念上它们是相同的。
这样如何？

不过，对我来说，感觉它应该可以更好。这里重复遍历了字段、值，然后调用 `walk`，但概念上它们是相同的。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +如果 `value` 是一个 `reflect.String`。然后我们就像平常一样调用 `fn`。
这样如何？我觉得 then 不用翻译出来。

如果 `value` 是一个 `reflect.String`，我们就像平常一样调用 `fn`。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +一旦我们确定了这些东西，我们就可以遍历 `numberOfValues`，使用 `getField` 函数的结果调用 `walk` 函数。
> 一旦我们确定了这些东西

可以简化一下？`一旦确定了这些`

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +添加到测试用例中
`添加以下代码到测试用例中：`是否更自然一些？

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +_这是好的！_ 重构是一段旅程，有时我们会犯错误。TDD 的一个主要观点是它给了我们尝试这些东西的自由。
> This is OK!

可以翻译成`这没问题！`

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +为了解决这个问题，我们需要将带有映射的断言移动到一个新的测试中，在这个测试中我们不关心顺序。
这两行建议都用 map，之前 maps 那章好像没译成映射。另外 map 直写就可以，不用加行内代码标记。

2018-09-16 13:19 UTC, pityonline commented on zh-CN/reflection.md
> +- 在回顾中做了一个糟糕的重构，但并不会对此感到太沮丧。通过迭代地进行测试，这并不是什么大问题。
这样如何？

在回顾中做了一个糟糕的重构，但不用对此感到太沮丧。通过迭代地测试，这并不是什么大问题。

2018-09-16 13:32 UTC, pityonline commented on zh-CN/reflection.md
> +不能对指针 `Value` 使用 `NumField`，我们需要在使用 `Elem()` 之前提取底层值。
感觉这里是说你不能对指针的值使用 `NumField`，请 @polaris1119 @flw-cn 方便时也看看。

2018-09-17 06:36 UTC, polaris1119 commented on zh-CN/reflection.md
> +不能对指针 `Value` 使用 `NumField`，我们需要在使用 `Elem()` 之前提取底层值。
@pityonline 指针的 reflect.Value 类型不能使用 NumField，必须先调用 Elem 之后才能调用 NumField

2018-09-18 14:51 UTC, pityonline requested changes
@Donng 除一个错别字外未发现其它问题，可以 rebase 合并 commits，然后更新翻译进度了。

2018-09-18 14:51 UTC, pityonline commented on zh-CN/reflection.md
> +指针类型的 `Value` 不能使用 `NumField` 方法，在执行此方法前需要掉用 `Elem()` 提取底层值。
`掉用`应该是`调用`。

2018-09-20 03:57 UTC, pityonline commented on zh-CN/schedule.md
> +* [ ] [反射](reflection.md)
这里应该是已完成标记？

2018-09-20 04:16 UTC, pityonline approved these changes

2018-09-20 04:16 UTC, merged