hello-world 内容更新
studygolang/learn-go-with-tests pull request #37
Opened 2019-05-26 03:20 UTC by Donng

2019-07-02 01:38 UTC, pityonline requested changes
Review 完成，请查阅评论。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +按照传统，我们使用新语言编写的第一个程序都是 Hello，world。
建议：`使用` => `学习`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +如果你使用的是基于 unix 的系统，你的名字是「bob」并且很乐于遵循 Go 关于 `$GOPATH` 的约定（这是最简单的设置方式）。那么你可以执行以下命令 `mkdir -p $GOPATH/src/github.com/bob/hello` 快速创建目录。
Unix 是专有名词，一般写作 UNIX 或 Unix。原文建议也更正一下。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +`func` 关键字用来定义带有名称和主体的函数。
> `func` 关键字通过一个名称和函数体来定义函数。

这样如何？

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +你会如何测试这个程序？将你「领域」内的代码和外部世界（会引起副作用）分离开会更好。`fmt.Println` 会产生副作用（打印输出到 stdout），我们发送的字符串在自己的领域内。[^注1]
建议：`打印输出到 stdout` => `打印到标准输出`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  - 测试函数的命名必须从单词 `Test` 开始
建议：`从` => `以`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +现在这些信息足以让我们明白，类型为 `*testing.T` 的变量 `t` 是你在测试框架中的 "hook"（钩子），所以当你可想让测试失败时可以执行 `t.Fail()` 之类的操作。
`所以当你可想让测试失败时` 多了一个 `可` 字。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  **if**
原文格式有更新，建议一起改掉。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> 我们使用 `varName := value` 的语法声明变量，它允许我们在测试中重用一些值使代码更具可读性。

上面一行改成这样如何？

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +我们正在调用 `t` 的 `Errorf` 方法，该方法将打印一条消息并使测试失败。`f` 表示格式化，它允许我们构建一个字符串，并将值插入占位符值 `%s` 中。当你测试失败时，它能够让你清楚测试是如何运行的。
> 我们调用 `t` 的 `Errorf` 方法打印一条消息并使测试失败。

这样如何？

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +让我们从在测试中捕获这些需求开始。这是基本的测试驱动开发，可以确保我们的测试用例 *确实* 是如我们所想的在测试。当你回顾编写的测试时，会发现一个风险：即使代码没有按照预期工作，测试也可能继续通过。
这里感觉之前的翻译更好一些。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  编辑 `Hello` 函数以接受字符串类型的参数
方便的话这里也可以改一下，`编辑` => `修改`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  为了使测试通过，我们使用 name 参数并用 `Hello` 字符串连接它，
方便的话这里也可以改成：

> 为了使测试通过，我们使用 `name` 参数并用 `Hello,` 字符串连接它，

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  当你运行测试时，现在应该通过了。通常作为 TDD 周期的一部分，我们现在应该 *重构* 测试。
这里可以改成这样，更顺畅一些。

> 现在再运行测试就应该通过了。通常作为 TDD 周期的一部分，我们该着手 *重构* 了。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +### 版本控制说明
建议改成：

> ### 关于版本控制的一点说明

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +此时，如果你正在使用版本控制（你应该这样做！）我将按原样`提交`代码。因为我们拥有一个测试支持的工作软件。
建议改成这样：

> 此时，如果你正在使用版本控制（你应该这样做！）我将按原样 **提交** 代码。因为我们拥有一个经测试保证的可用软件。

原文中 `commit` 其实是为了着重说明，而非代码，不建议使用行内代码格式。我会向上游提个 PR 修改这里。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +不过我不会推送到主分支上，因为我下一步计划重构。现在提交很合适，当重构中陷入混乱时你总是可以回到工作版本。
`工作` => `可用`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> 常量的定义如下

建议改成：

> 通过我们这样定义一个常量

根据上下文，这里不是介绍 *常量* 的概念，而是定义一个常量的语法示例。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +这种方法的好处是，你可以建立在其他测试中也能够使用的共享代码。
`其他` => `其它`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +重构不 *仅仅* 是为了生产环境的代码！
建议改成：

> 重构不 *仅仅* 是针对程序的代码！

这里的 **production code** 并非指的是生产环境的代码，而是指程序代码本身，和下文中的测试用例中的代码相对应。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +我们将断言重构为函数。这减少了重复并且提高了测试的可读性。在 Go 中，你可以在其他函数中声明函数并将它们分配给变量。你可以像普通函数一样调用它们。我们需要传入 `t *testing.T`，这样我们就可以在需要的时候令测试代码失败。
建议改成这样：

> 我们将断言重构为函数。这减少了重复并且提高了测试的可读性。在 Go 中，你可以在其它函数中声明函数并将它们分配给变量。你可以像调用普通函数一样调用它们。我们需要传入 `t *testing.T`，这样就可以在需要的时候令测试代码失败。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  如果我们运行测试，应该看到它满足了新的要求，并且我们没有意外地破坏其他功能。
`其他` => `其它`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +现在我们对代码很满意，我将修改之前的提交，所以我们只提交代码好的版本及其测试。
`代码好的` 建议改成 `认为好的`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  - 让编译器通过
这里也改一下吧，应该是让`编译`通过，而不是`编译器`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +- 运行测试，查看失败原因并检查错误消息是很有必要的
原文是 `meaningful` 应该是有含义的，有意义的，我觉得之前的用词更好一些。可能作者是要表达 `error message which is meaningful` 但少个 `which` 不太通顺。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  我们应该确信，我们可以使用 TDD 轻松实现这一功能！
这里可以改一下。

> 通过 TDD 轻松实现这一功能，我们是有信心的！

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +为使用西班牙语的用户编写测试，将其添加到现有套件。
`套件`感觉有些硬，不如换成`的测试用例中`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  hello_test.go:29: got 'Hola, Elodie' want 'Hello, Elodie'
上一段中有个`其他`换成`其它`。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
>  - 如果没有其他 `case` 语句匹配，将会执行 `default` 分支
`其他`换成`其它`，这个列表里所有缺少`。`的行都补充一下吧。

2019-07-02 01:38 UTC, pityonline commented on zh-CN/hello-world.md
> +与「现实世界」的软件相比，这当然是微不足道的，但原则依然成立。TDD 是一门需要通过开发去实践的技能，但通过将问题分解成更小的可测试的组件，你编写软件将会更加轻松。
`成立`建议换成`通用`。

> TDD is a skill that needs practice to develop but by being able to break problems down into smaller components that you can test you will have a much easier time writing software.

`a skill that needs practice to develop` 应该是指通过练习来培养（开发）一种技能。`but` 这个连词可以不译。

2019-07-03 07:54 UTC, Donng commented
@pityonline 已按内容修改。除了 `其它`，查了一下：`其他`是很早就有的词汇了，可指人指物；后来又出现了“其它”，一开始是不规范的用法，后来习非成是，但是只能用来指物。

所以都统一用`其他`了。

2019-07-04 02:42 UTC, pityonline commented
> @pityonline 已按内容修改。除了 `其它`，查了一下：`其他`是很早就有的词汇了，可指人指物；后来又出现了`其它`，一开始是不规范的用法，后来习非成是，但是只能用来指物。
> 
> 所以都统一用`其他`了。

我查了一下，果然是！看来我从小就学了很多新世界的东西……

我这两天会针对你的修订再校对一遍，已经修订过的问题都标记为已解决吧。

2019-07-13 02:30 UTC, pityonline commented on zh-CN/hello-world.md
>  **if**
这里要不要改一下？原文改成这样了，另一个类似的 ``t.Errorf`` 也是。

```
#### `if`
```

2019-07-13 02:37 UTC, pityonline commented on zh-CN/hello-world.md
Sorry。这里的 `通过` 应该是 `通常`，笔误了。

2019-07-13 02:43 UTC, pityonline requested changes
@Donng 还有两个未 resolve 的小问题，麻烦再看一下。

2019-07-21 08:48 UTC, pityonline approved these changes
LGTM. 这三个 commits 是否要 rebase 成一个？不需要的话我就合并了？ @Donng

2019-07-22 02:10 UTC, Donng commented
@pityonline 已合并

2019-07-23 01:09 UTC, merged