【翻译更新】更新integers的内容
studygolang/learn-go-with-tests pull request #50
Opened 2019-10-16 02:47 UTC by Donng

2019-10-17 00:54 UTC, pityonline commented
@Donng rebase 到最新的 master 上吧，记得 PR 前先检查一下你的分支是否是从最新的 master 上 checkout 出来的。

2019-10-17 02:21 UTC, Donng commented
@pityonline OK，已 rebase

2019-10-18 00:45 UTC, pityonline requested changes
@Donng 有几处小问题，请看一下。

2019-10-18 00:45 UTC, pityonline commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
`更深入的了解测试`中`的`换成`地`吧。

2019-10-18 00:45 UTC, pityonline commented on zh-CN/integers.md
> +如果你的代码发生更改，使得示例不再有效，那么你的构建（build）也会失败。
原译文中用`导致`没问题。

2019-10-18 00:45 UTC, pityonline commented on zh-CN/integers.md
> +如果你将带有示例的代码发布到一个公共 URL，您可以在 [godoc.org](https://godoc.org) 上共享代码的文档。例如，这是本章最终的API文档 [https://godoc.org/github.com/quii/learn-go-with-tests/integers/v2](https://godoc.org/github.com/quii/learn-go-with
中英文之间注意空白，这个 godoc.org 的长 URL 不用使用链接语法，URL 会自动生成链接。

2019-10-18 02:21 UTC, Donng commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
的地得在新课标似乎慢慢不再区分了

2019-10-18 03:35 UTC, Donng commented
@pityonline 长链接去掉 `()[]` 不能通过测试，其他部分已修改。

2019-10-20 06:46 UTC, pityonline commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
有来源吗？不区分没问题，但我还是想了解下。

2019-10-20 06:47 UTC, pityonline commented on zh-CN/integers.md
> +如果你将带有示例的代码发布到一个公共 URL，您可以在 [godoc.org](https://godoc.org) 上共享代码的文档。例如，这是本章最终的API文档 [https://godoc.org/github.com/quii/learn-go-with-tests/integers/v2](https://godoc.org/github.com/quii/learn-go-with
是我搞错了，Markdown 没有祼 URL 的语法。不过 `最终的API文档` 中应该适当添加空格。

2019-10-20 11:24 UTC, Donng commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
也不是不分了，就是开始有那个趋势了 
https://www.zhihu.com/question/20062004/answer/91159841

2019-10-20 11:31 UTC, pityonline commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
我看了那个问题，坚定了要区分的原则。——没想到是刘江提问的，东东枪还跑去回答了。

2019-10-20 11:37 UTC, Donng commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
我是不喜欢分，觉得麻烦一般都用`的`

2019-10-20 12:07 UTC, Donng commented on zh-CN/integers.md
> +如果你将带有示例的代码发布到一个公共 URL，您可以在 [godoc.org](https://godoc.org) 上共享代码的文档。例如，这是本章最终的API文档 [https://godoc.org/github.com/quii/learn-go-with-tests/integers/v2](https://godoc.org/github.com/quii/learn-go-with
@pityonline 原文显示已经加了，不知道为什么这里没显示出来

2019-10-20 12:33 UTC, pityonline commented on zh-CN/integers.md
> +你可以通过编写 [示例](https://blog.golang.org/examples) 更深入的了解测试，标准库的文档中能够找到许多这样的例子。
一个字，用对了省很多麻烦，用错了可能导致很多问题。当然一般来说都不严重，平时还是稍严谨一些，没什么操作难度的小动作免掉一些不必要的麻烦也是值得的。

2019-10-20 12:41 UTC, pityonline approved these changes

2019-10-20 12:42 UTC, merged