integers
studygolang/learn-go-with-tests pull request #7
Opened 2018-06-14 01:51 UTC by Donng

2018-06-14 01:57 UTC, pityonline commented
PR 标题和 commit message 建议保持原有风格，参考 #5。

2018-06-14 02:19 UTC, Donng commented
@pityonline 现在这样 ok 吗？

2018-06-14 06:12 UTC, flw-cn requested changes
其它部分没有异议。

2018-06-14 06:12 UTC, flw-cn commented on zh-CN/integers.md
> +**[你可以在这里找到本章的所有代码](https://github.com/quii/learn-go-with-tests/tree/master/hello-world)**
这个链接不对。

2018-06-14 06:12 UTC, flw-cn commented on zh-CN/integers.md
> +还需要注意的是，我们不再使用 main 包，而是定义了一个名为 integers 的包。顾名思义，它将对处理整数的函数进行分组，例如 Add。
这里用 `分组` 不够通顺，是否可以译作 `聚集` 更佳？比如下面这样：

> 顾名思义，它将聚集那些处理整数的函数，例如 Add。

2018-06-14 06:12 UTC, flw-cn commented on zh-CN/integers.md
> +我们可以编写另一个测试，用一些不同的数字来迫使测试失败，但那感觉就像猫鼠游戏。
只是一个小小的建议， `猫鼠游戏` 是否可以翻译成 `猫捉老鼠`？

2018-06-14 06:13 UTC, Donng commented on zh-CN/integers.md
> +**[你可以在这里找到本章的所有代码](https://github.com/quii/learn-go-with-tests/tree/master/hello-world)**
@flw-cn   Emmmm   见笑了...

2018-06-14 06:18 UTC, polaris1119 requested changes

2018-06-14 06:18 UTC, polaris1119 commented on zh-CN/integers.md
> +**[你可以在这里找到本章的所有代码](https://github.com/quii/learn-go-with-tests/tree/master/hello-world)**
源码链接错了

2018-06-14 06:18 UTC, polaris1119 commented on zh-CN/integers.md
> +**注意：** 每个目录中的 Go 源文件只能有一个包（package），请确保你的文件是分开组织的。[这里对此作了一个很好的解释](https://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project)。
建议：每个目录中的 Go 源文件只能属于一个包（package）。

这里是否需要说明下，`_test.go` 文件可以属于另外的包，从这个角度来说，这句不是很严谨。

2018-06-14 06:18 UTC, polaris1119 commented on zh-CN/integers.md
> +如果你注意一下就会发现，我们在上一节中学习了 *命名返回值*，但没有在这里使用。它通常应该在结果的含义在上下文中不明确时使用，在我们的例子中，`Add` 函数将参数相加是非常明显的。 你可以参考 [这个](https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters) wiki 获取更多细节。
原文「上一节」是有链接的。

2018-06-14 06:18 UTC, polaris1119 commented on zh-CN/integers.md
> +请注意，如果删除注释 「//Output: 6」，示例函数将不会执行。虽然函数将被编译，但是它不会执行。
虽然函数将被编译，但是它不会执行。 -> 虽然函数会被编译，但是它不会执行。

2018-06-14 06:18 UTC, polaris1119 commented on zh-CN/integers.md
> +**[你可以在这里找到本章的所有代码](https://github.com/quii/learn-go-with-tests/tree/master/hello-world)**
发现重复了。哈哈哈，我也校对了~

2018-06-14 06:29 UTC, Donng commented on zh-CN/integers.md
> +还需要注意的是，我们不再使用 main 包，而是定义了一个名为 integers 的包。顾名思义，它将对处理整数的函数进行分组，例如 Add。
> 它将处理整数的函数进行分类

`聚集` 对应 `aggregation`，我觉得也不太合适。上面这个怎么样？

2018-06-14 06:34 UTC, Donng commented on zh-CN/integers.md
> +我们可以编写另一个测试，用一些不同的数字来迫使测试失败，但那感觉就像猫鼠游戏。
> In a fight or contest, if one person plays cat and mouse, or a game of cat and mouse, with the other, the first person tries to confuse or deceive the second in order to defeat them.

`猫鼠游戏` 算是一个谚语了。

2018-06-14 07:21 UTC, Donng commented on zh-CN/integers.md
> +如果你注意一下就会发现，我们在上一节中学习了 *命名返回值*，但没有在这里使用。它通常应该在结果的含义在上下文中不明确时使用，在我们的例子中，`Add` 函数将参数相加是非常明显的。 你可以参考 [这个](https://github.com/golang/go/wiki/CodeReviewComments#named-result-parameters) wiki 获取更多细节。
@polaris1119  这里暂时用原英文的链接了

2018-06-14 07:39 UTC, Donng commented on zh-CN/integers.md
> +**注意：** 每个目录中的 Go 源文件只能有一个包（package），请确保你的文件是分开组织的。[这里对此作了一个很好的解释](https://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project)。
@polaris1119 这违背了 Go 的原则吧

2018-06-14 08:39 UTC, flw-cn commented on zh-CN/integers.md
> +还需要注意的是，我们不再使用 main 包，而是定义了一个名为 integers 的包。顾名思义，它将对处理整数的函数进行分组，例如 Add。
`group` 可以对应汉语 `聚集`，在这里用 `聚集` 没有问题。中英文本来就是多对多的关系。

2018-06-14 08:42 UTC, flw-cn commented on zh-CN/integers.md
> +**注意：** 每个目录中的 Go 源文件只能有一个包（package），请确保你的文件是分开组织的。[这里对此作了一个很好的解释](https://dave.cheney.net/2014/12/01/five-suggestions-for-setting-up-a-go-project)。
嗯，这里没有必要为了严谨而往错误的方向引导。

BTW：你不说我都不知道 _test.go 可以写另一个 package……

2018-06-14 08:44 UTC, flw-cn approved these changes

2018-06-14 08:50 UTC, flw-cn commented on zh-CN/integers.md
> +如果你真想多测试的更加深入，可以写一些 [示例](https://blog.golang.org/examples)。你将在标准库的文档中找到许多示例。
关于这个修改的基础规范现在是否已经有了？ @Donng @polaris1119 @pityonline

2018-06-14 11:54 UTC, pityonline requested changes
@Donng 我发现有两个处小问题，请参考。

2018-06-14 11:54 UTC, pityonline commented on zh-CN/integers.md
> +如果你注意一下就会发现，我们在 [上一节](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/hello-world) 中学习了 *命名返回值*，但没有在这里使用。它通常应该在结果的含义在上下文中不明确时使用，在我们的例子中，`Add` 函数将参数相加是非常明显的。 你可以参考 [这个](https://github.com/
> ...是非常明显的。 你可以参考...

全角中文标点后不要再插入空白了，否则看上去会多出一块空白。

2018-06-14 11:54 UTC, pityonline commented on zh-CN/integers.md
> +如果你注意一下就会发现，我们在 [上一节](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/hello-world) 中学习了 *命名返回值*，但没有在这里使用。它通常应该在结果的含义在上下文中不明确时使用，在我们的例子中，`Add` 函数将参数相加是非常明显的。 你可以参考 [这个](https://github.com/
有一种全角中文标点后插入空白的场景，就是缺少这个空白会导致渲染不正常，那种场景是必须的。

2018-06-14 11:54 UTC, pityonline commented on zh-CN/integers.md
> +如果你真想多测试的更加深入，可以写一些 [示例](https://blog.golang.org/examples)。你将在标准库的文档中找到许多示例。
链接文本周围是否插入空白都是允许的，这行在修改之前属于正确，现在的修改属于非必须的。如形成统一规范也可以，不过这都是要人工编写和检查的。

2018-06-15 01:19 UTC, Donng commented
@pityonline 这里是我疏忽忘了加空白，为了保持跟前文统一风格做的修改。

2018-06-15 02:47 UTC, Donng commented
@pityonline  @polaris1119  没有问题就可以 `merge` 了

2018-06-15 03:07 UTC, pityonline approved these changes

2018-06-15 03:46 UTC, polaris1119 approved these changes

2018-06-15 03:46 UTC, merged