校对 arrays-and-slices.md
studygolang/learn-go-with-tests pull request #9
Opened 2018-06-16 02:36 UTC by Donng

对照 [arrays-and-slices](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/arrays-and-slices)，原译者个人简化了很多，翻译对照博客所以内容也有出入，修订内容较多。

@pityonline  @polaris1119  @flw-cn

2018-06-16 03:41 UTC, pityonline requested changes
@Donng 我提了一些小的修改建议，请查阅。

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
>  我们可以使用 `range` 语法来让函数变得更加整洁。
[原文](https://github.com/studygolang/learn-go-with-tests/blob/master/arrays-and-slices.md#refactor)已为 range 添加了链接：

```
Let's introduce [`range`](https://gobyexample.com/range) to help clean up our code
```
建议一起修订。

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +我们会使用 [切片类型](https://golang.org/doc/effective_go.html#slices)，它可以接收不同大小的切片集合。语法上和数组非常相似，只是在声明的时候不指定长度：
建议和原文的链接格式保持一致，因为这样会导致与原文行号变化较大。如在原文更换链接时，只需要改 reference 里的链接地址，现在的方式就需要改这行内容了，在校对时会认为这行内容发生了很长的变化，但实际变化却很小，不容易突出`关键变更`。参考 [markdown/syntax#link](https://daringfireball.net/projects/markdown/syntax#link)：

> Reference-style links use a second set of square brackets, inside which you place a label of your choosing to identify the link:
>
> This is [an example][id] reference-style link.

下同。

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +这里有一种创建切片的新方式。`make` 可以在创建切片的时候指定我们需要的长度和容积。
*容积*翻译成**容量**是否会好一点儿？

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
>  这样使用起来更加方便，而且还能增加代码的类型安全性。如果一个粗心的开发者使用 `checkSums(t,got,"dave")` 是不能通过编译的。
原文是 `checkSums(t, got, "dave")`，建议一并修订。

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +```
原文有指定代码块语法为 `bash`，建议与原文保持一致。

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +  - 切片的容积是 *固定* 的，但是你可以使用 `append` 从原来的切片中创建一个新切片
*容积* => **容量**？

2018-06-16 03:41 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +  - 如何获取部分切片
建议使用与原文一致的 `*` 无序列表标记。

2018-06-16 04:07 UTC, Donng commented on zh-CN/arrays-and-slices.md
> +  - 切片的容积是 *固定* 的，但是你可以使用 `append` 从原来的切片中创建一个新切片
我会把所有容积都替换为容量

2018-06-16 04:08 UTC, Donng commented on zh-CN/arrays-and-slices.md
> +  - 如何获取部分切片
@pityonline 无序列表 `+` 、`-`、 `*`，都是等同的效果，不过这里还是遵循原文。

2018-06-16 06:10 UTC, pityonline requested changes
@Donng 发现几个小问题，请查阅。

2018-06-16 06:10 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +* [...]type{value1, value2, ..., valueN}  e.g. `numbers := [...]int{1, 2, 3, 4, 5}`
原文在这里对 `[xxx]` 作了转义，否则有些编辑器的语法提示工具会提示：No link definition for link ID 'xxx'，建议与原文保持一致。

2018-06-16 06:10 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +---
分割线上下都应有一个空行，避免出现渲染错误。

2018-06-16 06:10 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +本文由 [GCTT](https://github.com/studygolang/GCTT) 原创编译，[Go 中文网](https://studygolang.com/) 荣誉推出
文件尾提示 `\ No newline at end of file` 需要插入必须的空行。

2018-06-16 06:10 UTC, pityonline commented on zh-CN/arrays-and-slices.md
>  func TestSumAll(t *testing.T)  {
有些地方用了两个空格，原文中也一样，建议一并修订。

2018-06-16 07:59 UTC, Donng commented on zh-CN/arrays-and-slices.md
>  func TestSumAll(t *testing.T)  {
@pityonline 哪里两个空格

2018-06-16 09:52 UTC, pityonline commented on zh-CN/arrays-and-slices.md
>  func TestSumAll(t *testing.T)  {
`func TestSumAll(t *testing.T)空格空格{`，其它地方也有这样写的。

2018-06-17 01:55 UTC, pityonline commented on zh-CN/arrays-and-slices.md
> +* \[...\]type{value1, value2, ..., valueN}  e.g. `numbers := [...]int{1, 2, 3, 4, 5}`
这两行里的空格请一并修正吧，`valueN}空格空格e.g.`。

2018-06-17 03:01 UTC, pityonline approved these changes

2018-06-17 03:01 UTC, merged